apiVersion: apps/v1
kind: Deployment
metadata:
  name:  chatapp-authorization
  namespace: chatapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-authorization
  template:
    metadata:
      labels:
        app: chatapp-authorization
    spec:
      containers:
        - name: chatapp-authorization
          image:  zilvinas0147/chatapp-authorization:v1.5.2
          ports:
            - containerPort: 8080