spring:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_user
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: authorization
  profiles:
    active: dev
  config:
#    choose port 9999 (non existent) if running outside docker
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://localhost:9999

app:
  authorizedRedirectUris:
    - "http://localhost:4200/oauth2/redirect"
  tokenExpirationMsec: 864000000
  tokenSecret: "${TOKEN_SECRET}"